public enum UserStatus {
    PROFESSORA, PROFESSOR, PESQUISADORA, PESQUISADOR,
    GRADUANDA, GRADUANDO, MESTRANDA, MESTRANDO, DOUTORANDA, DOUTORANDO,
    DESENVOLVEDORA, DESENVOLVEDOR, TESTADORA, TESTADOR, ANALISTA,
    TÉCNICA, TECNICA, TÉCNICO, TECNICO,
    GRADUADO, GRADUADA, MESTRE, MESTRA, DOUTOR, DOUTORA;
}
